import { useEffect, useState } from 'react'
import { api, ApiError, type AdminDashboard } from '../../shared/api/client'
import { branchDateValue } from '../../shared/time'

export function AdminDashboardPage() {
  const [from, setFrom] = useState(branchDateValue); const [to, setTo] = useState(branchDateValue)
  const [data, setData] = useState<AdminDashboard | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = () => { setLoading(true); setError(''); api.getAdminDashboard(from, to).then(setData).catch(cause => setError(cause instanceof ApiError ? cause.message : 'Không thể tải dashboard.')).finally(() => setLoading(false)) }
  useEffect(load, [from, to])
  return <div className="page-stack command-center"><div className="page-header"><div><p className="page-kicker">System admin</p><h2>Trung tâm điều hành</h2><p>Theo dõi chỉ số tổng quan và hiệu suất giữa các chi nhánh.</p></div><div className="inline-actions"><label>Từ<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>Đến<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label><button className="button button-secondary" onClick={load}>Làm mới</button></div></div>{loading ? <div className="ui-skeleton"><span /><span /><span /></div> : error ? <div className="ui-state" role="alert"><strong>Không thể tải dữ liệu</strong><p>{error}</p><button className="button button-secondary" onClick={load}>Thử lại</button></div> : <><div className="metric-grid">{data?.metrics.map(metric => <article className="metric" key={metric.label}><span>{metric.label}</span><strong>{metric.format === 'currency' ? `${metric.value.toLocaleString('vi-VN')} ₫` : metric.value}</strong></article>)}</div><section className="surface"><div className="section-heading"><div><h2>Hiệu suất chi nhánh</h2><p>So sánh theo khoảng thời gian đã chọn.</p></div></div><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Chi nhánh</th><th>Booking</th><th>Hoàn thành</th><th>No-show</th><th>Thực thu</th></tr></thead><tbody>{data?.branches.map(branch => <tr key={branch.branchId}><td><strong>{branch.branchName}</strong></td><td>{branch.bookings}</td><td>{branch.completionRate}%</td><td>{branch.noShowRate}%</td><td>{branch.netAmount.toLocaleString('vi-VN')} ₫</td></tr>)}</tbody></table></div></section></>}</div>
}
